package elemental3;

import javax.annotation.Generated;
import jsinterop.annotations.JsPackage;
import jsinterop.annotations.JsType;

/**
 * The WebGLTransformFeedback interface is part of the WebGL 2 API and enables transform feedback, which is the process of capturing primitives generated by vertex processing. It allows to preserve the post-transform rendering state of an object and resubmit this data multiple times.
 *
 * @see <a href="https://developer.mozilla.org/en-US/docs/Web/API/WebGLTransformFeedback">WebGLTransformFeedback - MDN</a>
 */
@Generated("org.realityforge.webtack")
@JsType(
    isNative = true,
    namespace = JsPackage.GLOBAL,
    name = "WebGLTransformFeedback"
)
public class WebGLTransformFeedback extends WebGLObject {
  WebGLTransformFeedback() {
  }
}
